version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@mikael"
    assignees:
      - "@mikael"
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"
      include: "scope"

  # Backend dependencies  
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "weekly" 
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@mikael"
    assignees:
      - "@mikael"
    commit-message:
      prefix: "maven"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "@mikael"
    assignees:  
      - "@mikael"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly" 
    open-pull-requests-limit: 5