spring:
  devtools:
    add-properties: true
  # Mail Configuration (disabled for development)
  mail:
    host: localhost
    port: 587
    debug: false
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# Server Configuration for IntelliJ
server:
  port: 8080
  address: localhost

# Security Configuration (disabled for development)
security:
  enable-csrf: false

# Frontend Development Server Configuration
app:
  frontend:
    dev-server:
      enabled: true
      url: http://localhost:9000

# Email Reminder Configuration (disabled for development)
reminder:
  mail:
    username: dev@example.com
    password: dev-password

# Logging Configuration
logging:
  file:
    name: ./logs/server.log
  level:
    org.springframework.security: DEBUG