# src/test/resources/application.yml
# This file overrides settings from src/main/resources/application.yaml during tests

spring:
  # 1. Datasource for H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL # H2 in-memory with PostgreSQL compatibility
    driver-class-name: org.h2.Driver
    username: sa
    password: # Empty password for H2 in-memory

  # 2. JPA/Hibernate for H2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # Use H2 dialect
    hibernate:
      ddl-auto: create-drop # Essential for tests: create schema on startup, drop on shutdown
    properties:
      hibernate:
        default_schema: PUBLIC # H2 typically uses PUBLIC schema, not 'public' if case sensitive
        jdbc:
          lob:
            non_contextual_creation: true # Keep this if needed, but often not for H2 tests

  # 3. Liquibase for H2
  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml # Point to your existing changelog (XML is fine)
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL # Match H2 URL
    user: sa # Match H2 user
    password: # Match H2 password
    drop-first: true # Important for clean test runs, drops all objects before applying changelog
    enabled: true # Ensure Liquibase runs in tests

# 4. Exclude main datasource auto-configuration if conflicts persist (less common for @DataJpaTest, but a good fallback)
# spring.autoconfigure.exclude:
#   - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration