spring:
  profiles:
    active: "@activatedProperties@"

  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/dtime}
    username: ${DATABASE_USERNAME:dtime}
    password: ${DATABASE_PASSWORD:dtime_dev_password}

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true

  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/dtime}
    user: ${DATABASE_USERNAME:dtime}
    password: ${DATABASE_PASSWORD:dtime_dev_password}

  # Mail Configuration
  mail:
    debug: false
    host: smtp.gmail.com
    port: 587
    transport:
      protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false

# Logging Configuration
logging:
  level:
    org.springframework.web: INFO
    web: DEBUG
    se.dtime: WARN

# Security Configuration
security:
  enable-csrf: ${SECURITY_CSRF_ENABLED:true}

# Email Reminder Configuration
reminder:
  mail:
    username: ${MAIL_USERNAME:dummy@example.com}
    password: ${MAIL_PASSWORD:dummy-password}

# Application Configuration
dtime:
  system:
    start:
      date: 2025-01-01