spring:
  devtools:
    add-properties: true
  # Mail Configuration (disabled for development)
  mail:
    host: localhost
    port: 587
    debug: false
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# Server Configuration for Development (HTTPS enabled)
server:
  port: 8443
  http:
    port: 8080
  address: localhost
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/dtime_new.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD:dt2020}
    key-alias: dtime

# Security Configuration (disabled for development)
security:
  enable-csrf: false

# Frontend Development Server Configuration
app:
  frontend:
    dev-server:
      enabled: true
      url: https://localhost:9000

# Email Configuration (disabled for development)
mail:
  enabled: false
  username: dev@example.com
  password: dev-password

# Logging Configuration
logging:
  file:
    name: ./logs/server.log
  level:
    org.springframework.security: DEBUG